#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Import from the standard library
from os.path import split
import argparse
import pandas as pd
import webbrowser

# Import from happymonday
import happymonday
from happymonday.lib import try_me


def try_me():
    webbrowser.open("https://www.youtube.com/watch?v=mrZRURcb1cM")

if __name__ == '__main__':
    # For introspections purpose to quickly get this functions on ipython
    import happymonday
    try_me()

